# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlanYourTripWithCheero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlanYourTripWithCheero

pod 'FirebaseAuth'
  pod 'SDWebImage'
pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'MBProgressHUD'
pod 'lottie-ios'
  
end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
